const types = {
  SEARCH_USERS: "SEARCH_USERS",
  GET_USER: "GET_USER",
  CLEAR_USERS: "CLEAR_USERS",
  SET_LOADING: "SET_LOADING",
  SET_ALERT: "SET_ALERT",
  REMOVE_ALERT: "REMOVE_ALERT",
};

export default types;
